### ISSUE TITLE
How to NOT do my digital life?

### ISSUE THREAD

**Issue by enessmr** [GeorgeK1ng/XP2ESD#1]
My Digital life does not send EMAIL adress, so i need help

**Comment by GeorgeK1ng** [comment]
Congratulation spammer. Will never talk to you. You can find everything on that forum. I don’t care about your personal some kind of mail issue.

**Comment by enessmr** [comment]
> Congratulation spammer. Will never talk to you. You can find everything on that forum. I don’t care about your personal some kind of mail issue.

i will leak my emails to proof.
![image](https://github.com/user-attachments/assets/e3f8d5b6-2849-4778-80a6-470e7da97460)

**Comment by enessmr** [comment]
and i left less permission for infinity 
![image](https://github.com/user-attachments/assets/cf4b5e01-6d55-4370-8227-8d7f87e666c8)
